eureka:
  healthcheck:
    enabled: true
  client:
    healthcheck:
      enabled: true
    region: region-1
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST_PEER1:eureka1}:8761/eureka/,http://${EUREKA_SERVER_HOST_PEER2:eureka2}:8762/eureka/